name: Test
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Use this own repository
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/docs
      - name: Checkout to previous branch
        run: |
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD
      - name: Verify PR opened
        shell: bash
        run: |
          ./tests/check-simple-docs.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
