name: Test
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Use this own repository
      - uses: ./
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          docs-product: Internal Docs Test
          ref: test-case/docs
