name: Test E2E
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  setup_branches:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Setup git credentials
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "<>"
    - run: |
        ./scripts/create-test-branches.js
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_basic:
    runs-on: ubuntu-latest
    needs: setup_branches

    steps:
      - uses: actions/checkout@v3

      # Test case: should open PR with new docs
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/docs
      - name: Verify PR opened
        shell: bash
        run: tests/check-simple-docs.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check PR title and body
        shell: bash
        run: tests/check-pr-title-and-body.sh ${{ steps.action.outputs.pull-request-number }} $GITHUB_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_no_open_pr:
    runs-on: ubuntu-latest
    needs: setup_branches

    steps:
      - uses: actions/checkout@v3

      # Test case: should not open PR because docs haven't changed
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/upstream-docs-base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/no-docs-change
      - name: Verify PR not opened
        shell: bash
        run: tests/check-no-pr-open.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_docs_patch:
    runs-on: ubuntu-latest
    needs: setup_branches

    steps:
      - uses: actions/checkout@v3

      # Test case: should open PR with only docs patched
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/upstream-docs-base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/docs-patch
      - name: Verify PR opened with correct patch
        shell: bash
        run: tests/check-docs-patch.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_docs_delete:
    runs-on: ubuntu-latest
    needs: setup_branches

    steps:
      - uses: actions/checkout@v3

      # Test case: should open PR with only deleted docs
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/upstream-docs-base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/docs-renamed
      - name: Verify PR opened with correct patch
        shell: bash
        run: tests/check-docs-renamed.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
