name: 'Internal Docs Integration'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: ${{ secrets.VTEX_GITHUB_BOT_TOKEN }}
          docs-product: 'vtex-io'
