name: Test E2E
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test_basic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Test case: should open PR with new docs
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/docs
      - name: Checkout to previous branch
        run: |
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD
      - name: Verify PR opened
        shell: bash
        run: tests/check-simple-docs.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check PR title and body
        shell: bash
        run: tests/check-pr-title-and-body.sh ${{ steps.action.outputs.pull-request-number }} $GITHUB_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_no_open_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Test case: should not open PR because docs haven't changed
      - uses: ./
        id: action
        with:
          repo-owner: vtex
          repo-name: action-internal-docs
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-branch: test-case/no-docs-base
          docs-product: Internal Docs Test
          auto-merge: false
          ref: test-case/no-docs-change
      - name: Checkout to previous branch
        run: |
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD
      - name: Verify PR not opened
        shell: bash
        run: tests/check-no-pr-open.sh ${{ steps.action.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
